{{- if .Values.cloudflared.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: {{ .Values.cloudflared.namespace }}
  labels:
    app: cloudflared
type: Opaque
stringData:
  token: {{ .Values.cloudflared.token | quote }}
{{- end }}

