{{- if .Values.metallb.enabled }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2advertisement
  namespace: {{ .Values.metallb.namespace }}
  labels:
    app.kubernetes.io/name: metallb
spec:
  ipAddressPools:
  - default-pool
{{- end }}

