apiVersion: v2
name: observability
description: A Helm chart for observability stack (Grafana, Prometheus, Loki, Tempo, Alloy) optimized for Raspberry Pi
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: grafana
    version: 7.3.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: kube-prometheus-stack
    version: 58.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: loki
    version: 6.0.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: tempo
    version: 1.8.0
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled
  - name: alloy
    version: 0.1.0
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled

